import "./globals.css";
import "../../public/fonts/fonts.css";
export const metadata = {
  title: "Aximsoft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
